Update patch set 3
Patch Set 3:

Hi Derek,

yes this fixes build when targeting DSP variants :


FAILED: out/soong/.intermediates/external/skia/libskia/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libskia.so 
prebuilts/clang/host/linux-x86/clang-3859424/bin/clang++ out/soong/.intermediates/bionic/libc/crtbegin_so/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_core/crtbegin_so.o @out/soong/.intermediates/external/skia/libskia/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libskia.so.rsp out/soong/.intermediates/external/giflib/libgif/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/libgif.a out/soong/.intermediates/external/webp/src/libwebp-decode/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/libwebp-decode.a out/soong/.intermediates/external/webp/src/libwebp-encode/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/libwebp-encode.a out/soong/.intermediates/external/sfntly/libsfntly/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/libsfntly.a out/soong/.intermediates/external/compiler-rt/libcompiler_rt-extras/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/libcompiler_rt-extras.a out/soong/.intermediates/build/soong/libatomic/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/libatomic.a out/soong/.intermediates/build/soong/libgcc/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/libgcc.a out/soong/.intermediates/system/core/liblog/liblog/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/liblog.so out/soong/.intermediates/frameworks/native/opengl/libs/libGLESv2/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libGLESv2.so out/soong/.intermediates/frameworks/native/opengl/libs/libEGL/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libEGL.so out/soong/.intermediates/external/zlib/libz/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libz.so out/soong/.intermediates/external/expat/libexpat/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libexpat.so out/soong/.intermediates/external/libjpeg-turbo/libjpeg/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libjpeg.so out/soong/.intermediates/external/libpng/libpng/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libpng.so out/soong/.intermediates/external/icu/icu4c/source/common/libicuuc/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libicuuc.so out/soong/.intermediates/external/icu/icu4c/source/i18n/libicui18n/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libicui18n.so out/soong/.intermediates/external/freetype/libft2/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libft2.so out/soong/.intermediates/external/dng_sdk/libdng_sdk/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libdng_sdk.so out/soong/.intermediates/external/piex/libpiex/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libpiex.so out/soong/.intermediates/external/libcxx/libc++/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libc++.so out/soong/.intermediates/bionic/libdl/libdl/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libdl.so out/soong/.intermediates/bionic/libc/libc/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libc.so out/soong/.intermediates/bionic/libm/libm/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libm.so out/soong/.intermediates/bionic/libc/crtend_so/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_core/obj/bionic/libc/arch-common/bionic/crtend_so.o -o out/soong/.intermediates/external/skia/libskia/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_shared_core/libskia.so -nostdlib -Wl,--gc-sections -shared -Wl,-soname,libskia.so -target mipsel-linux-android -Bprebuilts/gcc/linux-x86/mips/mips64el-linux-android-4.9/mips64el-linux-android/bin -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--build-id=md5 -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--allow-shlib-undefined -Wl,--no-undefined-version -Wl,-melf32ltsmip
out/soong/.intermediates/external/skia/libskia/android_mips_mips32r2dsp-fp_mips32r2dsp-fp_static_core/obj/external/skia/src/core/SkBlitter_RGB16.o: In function `SkRGB16_Opaque_Blitter::blitMask(SkMask const&, SkIRect const&)':
external/skia/src/core/SkBlitter_RGB16.cpp:455: undefined reference to `blitmask_d565_opaque_mips(int, int, unsigned short*, unsigned int, unsigned char const*, unsigned int, unsigned int)'
clang.real: error: linker command failed with exit code 1 (use -v to see invocation)

Yes we are aware that upstream version removed DSP optimizations from skia, but since Android still uses skia with MIPS DSP optimizations, it's reasonable to have a functional build of them.

https://dmz-portal.mips.com/android/builders/master-MIPS32R2DSP-FP/builds/265

Patch-set: 3
Reviewer: Miodrag Dinic <1050647@85c56323-6fa9-3386-8a01-6480fb634889>