Update patch set 2
Patch Set 2:

Leon, patch set 2 contains -W related changes picked up from internal master.
I don't know if this will have merge conflict. Tree hogger will tell us later.
I saw the following warnings as errors for aosp_x86_64-eng target, but not for arm/arm64. Do you have fix for them?

 external/skia/src/gpu/gl/GrGLAssembleInterface.cpp:575:32: error: type 'GrGLInterface' requires 8 bytes of alignment and the default allocator only guarantees 4 bytes [-Werror,-Wover-aligned]
 external/skia/src/gpu/gl/GrGLAssembleInterface.cpp:81:32: error: type 'GrGLInterface' requires 8 bytes of alignment and the default allocator only guarantees 4 bytes [-Werror,-Wover-aligned]
 external/skia/src/gpu/gl/GrGLCreateNullInterface.cpp:822:72: error: type '(anonymous namespace)::NullInterface' requires 8 bytes of alignment and the default allocator only guarantees 4 bytes [-Werror,-Wover-aligned]
 external/skia/src/gpu/gl/GrGLInterface.cpp:39:28: error: type 'GrGLInterface' requires 8 bytes of alignment and the default allocator only guarantees 4 bytes [-Werror,-Wover-aligned]

Patch-set: 2
Reviewer: Chih-hung Hsieh <1052399@85c56323-6fa9-3386-8a01-6480fb634889>