Update patch set 4
Patch Set 4:

> Patch Set 4:
> 
> > Patch Set 4:
> > 
> > It has merge conflict with http://ag/3104940/ in the internal master. I will copy the change to the internal master once this CL in AOSP is approved.
> 
> I copied the change to internal master as changes to this Android.bp file are generated by the merge from skia.googlesource.com so I was going to assist with landing the change there.  However, It fails to compile first with linker errors in external/sfntly about missing symbols and after adding libandroidicu to it's Android.bp I get compiler errors about missing headers.
> 
> external/sfntly/cpp/src/sample/chromium/subsetter_impl.cc:26:10: fatal error: 'unicode/unistr.h' file not found

http://aosp/855009 in the same gerrit topic needs to be cherry-picked as well. I have removed 
'unicode/unistr.h' in the CL.

I am trying to get the font team to review my change.

Patch-set: 4
Reviewer: Gerrit User 1047684 <1047684@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=0