Update patch set 1
Patch Set 1: No score

Gerrit rejects changes to this git if author differs from commiter. The original author of this is Peter Eliasson <peter.eliasson.x@sonyericsson.com>. We really want to be open and keep the original author.

Error log from repo upload:
To ssh://johan.redestig@review.source.android.com:29418/platform/external/skia
 ! [remote rejected] Corrected-a-bug-in-SkPaint-breakText -> refs/for/master (you are not author peter.eliasson.x@sonyericsson.com)
error: failed to push some refs to 'ssh://johan.redestig@review.source.android.com:29418/platform/external/skia'

Patch-set: 1
Reviewer: Johan Redestig <1002951@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Code-Review=0