Update patch set 2
Patch Set 2:

> Leon, patch set 2 contains -W related changes picked up from
 > internal master.
 > I don't know if this will have merge conflict. Tree hogger will
 > tell us later.
 > I saw the following warnings as errors for aosp_x86_64-eng target,
 > but not for arm/arm64. Do you have fix for them?
 > 
 > external/skia/src/gpu/gl/GrGLAssembleInterface.cpp:575:32: error:
 > type 'GrGLInterface' requires 8 bytes of alignment and the default
 > allocator only guarantees 4 bytes [-Werror,-Wover-aligned]
 > external/skia/src/gpu/gl/GrGLAssembleInterface.cpp:81:32: error:
 > type 'GrGLInterface' requires 8 bytes of alignment and the default
 > allocator only guarantees 4 bytes [-Werror,-Wover-aligned]
 > external/skia/src/gpu/gl/GrGLCreateNullInterface.cpp:822:72: error:
 > type '(anonymous namespace)::NullInterface' requires 8 bytes of
 > alignment and the default allocator only guarantees 4 bytes
 > [-Werror,-Wover-aligned]
 > external/skia/src/gpu/gl/GrGLInterface.cpp:39:28: error: type
 > 'GrGLInterface' requires 8 bytes of alignment and the default
 > allocator only guarantees 4 bytes [-Werror,-Wover-aligned]

We disable that warning for certain platforms in our upstream builds [1][2]. But that doesn't get copied into our Android.bp file for a couple of reasons
- we only set the flag for 32-bit x86 (not sure whether that's because we don't see the warning, or because we don't have an x86_64 Android builder)
- Android.bp builds for multiple platforms, and doesn't trigger our condition of (if is_android && x86)

I think the fix would be to update Android.bp to contain the following:

        x86_64: {
            srcs: [
                ...
            ],
            cflags: [
                "-Wno-over-aligned",
            ],
        },

But I don't understand why you're not seeing that same warning for 32-bit. I also attempted to reproduce on Android's internal master, and I don't see the warning for either aosp_x86_64-eng or aosp_x86-eng.

[1] https://skia-review.googlesource.com/c/skia/+/2703
[2] https://groups.google.com/d/msg/skia-discuss/hU1IPFwU6bI/vIis9AbYBgAJ

Patch-set: 2
Reviewer: Leon Scroggins <1012974@85c56323-6fa9-3386-8a01-6480fb634889>