Update patch set 1
Patch Set 1:

reverted as this broke the standard x86 build.  In the case where SSSE3 is not present we will need to ensure that opts_check_SSE2.cpp does not reference functions defined in that file.

external/skia/src/opts/opts_check_SSE2.cpp:123: error: undefined reference to 'S32_opaque_D32_filter_DX_SSSE3(SkBitmapProcState const&, unsigned int const*, int, unsigned int*)'
external/skia/src/opts/opts_check_SSE2.cpp:129: error: undefined reference to 'S32_opaque_D32_filter_DXDY_SSSE3(SkBitmapProcState const&, unsigned int const*, int, unsigned int*)'
external/skia/src/opts/opts_check_SSE2.cpp:131: error: undefined reference to 'S32_alpha_D32_filter_DXDY_SSSE3(SkBitmapProcState const&, unsigned int const*, int, unsigned int*)'
external/skia/src/opts/opts_check_SSE2.cpp:125: error: undefined reference to 'S32_alpha_D32_filter_DX_SSSE3(SkBitmapProcState const&, unsigned int const*, int, unsigned int*)'

Patch-set: 1